---
- name: Bastion networking playbook 
  hosts: bastion 
  become: True
  tasks:
    
    - name: Checking Bastion internal network interfaces
      fail: 
        msg: "{{ host_interface }} not found in {{ ansible_facts.interfaces }}"
      when: host_interface not in ansible_facts.interfaces

    - name: Ensure firewalld is enabled and running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Adding interface {{ host_interface }} to internal zone
      command: nmcli con mod {{ host_interface }} connection.zone internal     

    - name: Adding Bastion interface {{ host_interface }} to firewall internal zone  
      firewalld:
        zone: internal
        interface: "{{ host_interface }}"
        permanent: yes
        state: enabled

    - name: Allow required service for internal zone
      firewalld:
        zone: internal
        state: enabled
        permanent: yes
        service: "{{ item }}"
      loop: "{{ services }}"

    - name: Allow tftp and pxe ports
      firewalld:
        zone: internal
        state: enabled
        permanent: yes
        port: "{{ item }}"
      loop: "{{ ports }}"

    - name: Reload Bastion firewalld service
      service:
        name: firewalld
        state: restarted 
