- name: Create nfs share and registry pv
  hosts: bastion
  become: True
  vars_files:
    - vars/vars.yml
  tasks:

    - name: Ensuring export registry directory dosen't exists
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - /exports/registry
        - /exports/ocp

    - name: Creating registry export
      file:
        state: directory
        path: "{{ item }}"
        mode: 0775
        owner: nobody
        group: nobody
      loop:
        - /registry
        - /ocp

    - name: Prepare disk
      parted:
        device: /dev/vdb
        number: 1
        part_end: 100GiB
        state: present  

    - name: Prepare second mount
      parted: 
        device: /dev/vdb
        number: 2
        part_start: 100GiB
        state: present      

    - name: Create xfs filesystem on /dev/sdb1
      filesystem:
        fstype: xfs
        dev: "{{ item }}"
      loop: 
        - /dev/vdb1
        - /dev/vdb2

    - name: Mount up device by label
      mount:
        path: /registry
        src: /dev/vdb1
        fstype: xfs
        state: mounted

    - name: Mount up device by label
      mount:
        path: /ocp
        src: /dev/vdb2
        fstype: xfs
        state: mounted

    - name: Creating exports file
      template:
        src: templates/nfs_exports.j2
        dest: /etc/exports.d/openshift.exports

    - name: Activating selinux boolean (virt_use_nfs)
      seboolean:
        name: virt_use_nfs
        state: yes
        persistent: yes
   
    - name: Restarting nfs
      service:
        name: nfs-server
        state: started
        enabled: true
