- name: Create nfs share and registry pv
  hosts: bastion
  become: True
  tasks:
    - name: Firing registry template patch
      template:
        src: templates/patch_registry.j2
        dest: /tmp/patch_registry.sh
        mode: '0755'
      
    - name: Applying patch
      command: /tmp/patch_registry.sh

    - name: Deleting temp files
      file:
        path: /tmp/patch_registry.sh
        state: absent
    
